DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS datas;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_hash TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  datas JSON DEFAULT '{}'
);

CREATE TABLE datas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_hash TEXT NOT NULL,
  object_date TIMESTAMP UNIQUE NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  datas JSON DEFAULT '{}'
);